name: Hi

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  welcome:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '3.1.x'

      - name: Welcome
        run: echo Welcome

  build:
    needs: welcome
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.x.x'

      - name: Build
        run: dotnet build 
  
  test:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.x.x'

      - name: Tests
        run: dotnet test
  
  publish:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.x.x'

      - name: Publish
        run: dotnet publish
